# Muestra el botón "Sponsor" en la cabecera del repositorio.
# Donaciones vía PayPal (juanesgtgt2@gmail.com).
custom: ["https://www.paypal.com/donate/?business=juanesgtgt2%40gmail.com&no_recurring=0&item_name=Apoyo%20a%20SKP%20E-Plumb&currency_code=USD"]
